---
title: "Useful tutorials and visualizations"
author: admin
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
categories: ["Statistics"]
tags: ["statistics", "tutorial"]
summary: Bunch of websites and tutorials found
---

## Linear model with normally distributed residuals:

- ['lm' r documentation](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/lm)

- [Tutorial](https://www.datacamp.com/community/tutorials/linear-regression-R)

## Linear model with other residuals distribution:

- [glm' r documentation](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/glm)

- [tutorial 1](https://www.datacamp.com/community/tutorials/generalized-linear-models)

- [tutorial 2](https://www.statmethods.net/advstats/glm.html)

## Non-linear models:

- by transforming your data: log, polynomial ... [tutorial](http://www.sthda.com/english/articles/40-regression-analysis/162-nonlinear-regression-essentials-in-r-polynomial-and-spline-regression-models/)

- by using the nls() function: [tutorial](https://www.r-bloggers.com/2016/02/first-steps-with-non-linear-regression-in-r/)

- (by building your own fitting and optimization functions and using a solver: [tutorial](https://www.magesblog.com/post/2013-03-12-how-to-use-optim-in-r/))

## General additive model: 

- a great [tutorial](https://noamross.github.io/gams-in-r-course/)

## Mixed effect models (using lm4):

- [tutorial 1](https://github.com/RoseannaGG/LinearMixedEffectsModels/blob/main/Linear%20Mixed%20Effects%20Models%20-%20R%20Gamlen-Greene.pdf)

- [tutorial 2](https://www.rensvandeschoot.com/tutorials/lme4/)

- [tutorial 3](https://ourcodingclub.github.io/tutorials/mixed-models/)

- [package vignette](https://cran.r-project.org/web/packages/lme4/vignettes/lmer.pdf)

- [nice visualization](https://www.tjmahr.com/plotting-partial-pooling-in-mixed-effects-models/) to understand the process behind Mixed-effect models

## Structural Equation Modeling:

- the Bible for SEM: [Jon Lefcheck book](https://jslefche.github.io/sem_book/)

- [tutorial](https://lavaan.ugent.be/tutorial/sem.html)

## Spatio-temporal analyses with R:

- The Bible for Spatio-temporal modeling: [book](https://spacetimewithr.org/index) ([pdf](https://spacetimewithr.org/Spatio-Temporal%20Statistics%20with%20R.pdf))

- Dealing with temporal auto-correlation in R: [tutorial](https://rpubs.com/markpayne/164550)

## Bayesian statistics:

- [an introduction](https://bookdown.org/content/4857/small-worlds-and-large-worlds.html#building-a-model)

- [lecture](https://github.com/benjamin-rosenbaum/bayesian-intro) using Stan

- [paper](https://www.nature.com/articles/s43586-020-00001-2)

## Machine learning

- Amazing visualization to understand and use machin learning analyses [website](https://mlu-explain.github.io/)
