---
title: "Hot in Press"
author: admin
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
categories: ["literature research"]
tags: ["literature"]
summary: Review of the articles we found in the past few weeks.
---
## In press this week
```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(googlesheets4)
library(dplyr)
library(kableExtra)
library(lubridate)

form = read_sheet("https://docs.google.com/spreadsheets/d/1RbL6vgRC_ZvTYL8Qh3uoAFBNeuach2gnLiNW92KxwAA/edit?usp=sharing")
form$Horodateur = form$Horodateur %>% stringr::str_sub(.,1,10) %>% as.Date(.,format = "%Y-%m-%d")

form = form[order(form$Horodateur,  decreasing = T),]

form = 
  form %>% 
  # distinct(Title, .keep_all = TRUE) %>% 
  distinct(`DOI (full URL)`, .keep_all = TRUE) %>%
  filter(!is.na(Title))

form %>% filter(Horodateur > (format(Sys.Date()-7, "%Y-%m-%d")) ) %>%
  mutate(text=paste("<b>", Title, "</b>", " <a href=\"",`DOI (full URL)`,"\">(DOI) </a> ", if(!is.na(Keywords)){Keywords}, if(!is.na(`Comments:`)){`Comments:`},sep="")) %>%
  select(text) %>%
  kable(., format = "html", escape = FALSE, col.names = NULL) %>%
  kable_styling(bootstrap_options = c("hover", "condensed")) 

```

## If you find something nice feel free to contribute

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSd53dAnWEsl-tP6eomio6LSx-zgUwd6s-SMEIX0960AQMptGA/viewform?embedded=true" height = "1000" width = "800" frameborder="0" marginheight="0" marginwidth="0">Chargement…</iframe>

## Previously in "Hot in Press"
### This month
```{r,echo=FALSE, warning=FALSE, message=FALSE}

if((format(Sys.Date()-7, "%Y-%m-%d"))>format(floor_date(as.Date(Sys.Date()), "month"), "%Y-%m-%d")){
  f = form %>% filter(Horodateur < (format(Sys.Date()-7, "%Y-%m-%d")) &
                  Horodateur > format(floor_date(as.Date(Sys.Date()), "month"), "%Y-%m-%d")) 
  if(nrow(f)>0){
    f %>%
  mutate(text=paste("<b>", Title, "</b>", " <a href=\"",`DOI (full URL)`,"\">(DOI) </a> ", if(!is.na(Keywords)){Keywords}, if(!is.na(`Comments:`)){`Comments:`},sep="")) %>%
  select(text) %>%
  kable(., format = "html", escape = FALSE, col.names = NULL) %>%
  kable_styling(bootstrap_options = c("hover", "condensed"))
  }
}

```

### This year
```{r,echo=FALSE, warning=FALSE, message=FALSE}
y = form %>% filter(Horodateur < format(floor_date(as.Date(Sys.Date()), "month"), "%Y-%m-%d") & 
                  Horodateur > format(floor_date(as.Date(Sys.Date()), "year"), "%Y-%m-%d")) 
if(nrow(y)>0){
  y %>%
  mutate(text=paste("<b>", Title, "</b>", " <a href=\"",`DOI (full URL)`,"\">(DOI) </a> ", if(!is.na(Keywords)){Keywords}, if(!is.na(`Comments:`)){`Comments:`},sep="")) %>%
  select(text) %>%
  kable(., format = "html", escape = FALSE, col.names = NULL) %>%
  kable_styling(bootstrap_options = c("hover", "condensed")) 
}


```

### Even before 
```{r,echo=FALSE, warning=FALSE, message=FALSE}
form %>% filter(Horodateur < format(floor_date(as.Date(Sys.Date()), "year"), "%Y-%m-%d")) %>%
  mutate(text=paste("<b>", Title, "</b>", " <a href=\"",`DOI (full URL)`,"\">(DOI)</a> ", if(!is.na(Keywords)){Keywords}, if(!is.na(`Comments:`)){`Comments:`},sep="")) %>%
  select(text) %>%
  kable(., format = "html", escape = FALSE, col.names = NULL) %>%
  kable_styling(bootstrap_options = c("hover", "condensed")) 

```