---
title: 'Plaisirs et présents 2022'
output: 
  html_document:
    toc: true
    toc_float: true
---

<body style="background-color:#E7FCB6;">

"juste au cas où?"

## Plaisirs du quotidien

-   Lunettes de soleil (demander à Célia)

-   Parfum: "Eau de Basilic Pourpre" Hermès ([parfum](https://www.hermes.com/fr/fr/product/eau-de-basilic-pourpre-eau-de-cologne-V105081V0/))

-   Pellicules photo argentique ISO 400 (ou ISO 100) plutôt en N&B ([exemple](https://www.pellicule-photo.com/produit/pellicules/films-135-24x36/negatif-noir-et-blanc/ilford-delta-400-135-36/))

## Voyage et balades

-   Etiquettes de voyage en cuir ([exemple](https://www.etsy.com/fr/listing/1146228885/etiquette-a-bagage-personnalisee-avec?gpla=1&gao=1&&utm_source=google&utm_medium=cpc&utm_campaign=shopping_fr_fr_fr_ps-e-bags_and_purses-other&utm_custom1=_k_CjwKCAjw79iaBhAJEiwAPYwoCBbOU9NlS95TAnsWweA6Du3fd1Im6cwUlbl3f9jYtJuZrU89klEmWhoCAnIQAvD_BwE_k_&utm_content=go_1774520388_69050005676_343176607137_pla-314261244147_c__1146228885frfr_468073391&utm_custom2=1774520388&gclid=CjwKCAjw79iaBhAJEiwAPYwoCBbOU9NlS95TAnsWweA6Du3fd1Im6cwUlbl3f9jYtJuZrU89klEmWhoCAnIQAvD_BwE))

<!-- -   Sac voyage cuir -->

<!-- -   Sac de tous les jours -->

## Sport

### Triathlon

-   Sac transition Triathlon ([Decathlon](https://www.decathlon.fr/p/sac-a-dos-de-transition-triathlon-aptonia/_/R-p-196551?mc=8585189))

-   Combinaison triathlon nage néoprène ([Decathlon 1](https://www.decathlon.fr/p/combinaison-neoprene-triathlon-sd-homme/_/R-p-307007?mc=8544852&c=NOIR), [Decathlon 2](https://www.decathlon.fr/p/combinaison-neoprene-triathlon-homme-zone-3-vista/_/R-p-X8764336?mc=8764336))

### Running

-   Chaussettes de course hautes (jusqu'au genoux - taille 42-47)

-   T-shirt de course (taille M)

-   Lycra manches longues (taille M - ex. [Decathlon](https://www.decathlon.fr/p/t-shirt-running-manches-longues-hiver-respirant-homme-kiprun-skincarebleu-mari/_/R-p-307913?mc=8588361&c=GRIS))

-   Chaussures trail Asic (pointure 44/45, drop 8mm, ex. [Decathlon](https://www.decathlon.fr/p/chaussure-de-trail-homme-asics-gel-trabuco-10-orange-noir/_/R-p-X8741660?mc=8741660), voir avec C?lia pour d?tails)

-   Short taille M (toujours utile)

### Vélo

-   Chaussettes de vélo (taille 42-47)

-   Chaussure cale-auto (pointure 44/45 - d'occasion)

-   Casque vélo (taille M - [Decathlon](https://www.decathlon.fr/p/casque-velo-route-roadr-500-mips/_/R-p-336288?mc=8669933&c=NOIR))

<!-- -   Radar Garmin ([Decathlon](https://www.decathlon.fr/p/radar-garmin-varia-rtl515/_/R-p-X8675596?mc=8675596)) -->

## Opération jardin

-   Programmateur arrosage automatique (sur pile pour arrosage automatique notre jardin [exemple](https://www.gammvert.fr/2-5030-produits-du-jardin/2-3921-nos-marques-entretenir-et-cultiver-le-jardin/3-3926-gardena/p-51044-programmateur-automatique-darrosage-a-pile-gardena-easy-plus-60-combinaisons), [exemple 2](https://www.gammvert.fr/2-5030-produits-du-jardin/2-3921-nos-marques-entretenir-et-cultiver-le-jardin/3-3926-gardena/p-51043-programmateur-automatique-darrosage-gardena-flex), [example 3](https://www.gammvert.fr/2-5030-produits-du-jardin/2-3921-nos-marques-entretenir-et-cultiver-le-jardin/3-3926-gardena/p-51044-programmateur-automatique-darrosage-a-pile-gardena-easy-plus-60-combinaisons))

-   Outils de jardinage (binette ...)

### Livres

-   Trait? Rustica du potager bio (occasion ou [FNAC](https://livre.fnac.com/a11825862/Christian-Dudouet-Le-traite-Rustica-du-potager-bio#omnsearchpos=5))

-   Agenda Rustica 2023 du potager ([FNAC](https://livre.fnac.com/a16996964/Robert-Elger-Agenda-Rustica-du-potager-2023#omnsearchpos=7))

-   L'encyclo Rustica du jardin en geste par geste (occasion ou [FNAC](https://livre.fnac.com/a11352680/Daniel-Brochard-L-encyclo-Rustica-du-jardin-en-geste-par-geste#omnsearchpos=2))

## Plus beau chien du quartier

-   Remorque de transport pour vélo (occasion ou [Decathlon](https://www.decathlon.fr/p/remorque-velo-bike-original-capacite-40-kg/_/R-p-X8597302?mc=8597302), [Trixie](https://www.trixie.de/fr/monde-des-produits/chien/en-voyage/accessoires-pour-velo/roulotte-de-velo-pour-chiens-1001093328-1001093357))

-   Nouveau collier lumineux pour balade de nuit (rose et rouge se voient bien)

-   Petit sac pour qu'elle porte ses propres cro(que)ttes ([exemple](https://www.maxizoo.fr/p/ruffwear-harnais-sac--dos-approach-orange-s-1280781/), voir avec C?lia)
