---
title: "Rémy Beugnon"
subtitle: "Curriculum vitae"
output: pdf_document
header-includes: \usepackage{hanging} \usepackage{setspace}\singlespacing \usepackage{floatrow} \usepackage{tabto} \usepackage{fancyhdr} \pagestyle{fancy} \fancyhead[L]{\textit{Rémy Beugnon}} \fancyhead[R]{\textit{Curriculum vitae}} 
---

# Education

```{=tex}
\begin{hangparas}{7.9em}{1}

\textit{2018 - 2021} \qquad\textbf{PhD. in Life Sciences}: Leipzig University, Leipzig, Germany.

\textit{2017 - 2018} \qquad \textbf{MSc. Ecology and Evolution}: Université Montpellier II, Montpellier, France.

\textit{2014 - 2018} \qquad \textbf{Agricultural engineering diploma}: Montpellier SupAgro, Montpellier, France.

\end{hangparas}
```
# Work history

```{=tex}
\begin{hangparas}{5em}{1}
\textit{2022-Present} 

\qquad \textbf{Postdoctoral researcher}: Leipzig Institute for Meteorology (LIM), German Center for Integrative Biodiversity Research (iDiv), Centre d'Ecologie Fonctionelle et Evolutive (CEFE), Montpellier, France. Project: "Vegetation diversity effects on microclimate: phenomenon and mechanisms" (supervision: Prof. Dr. Johannes Quaas, Dr. Stephan Hättenschwiler)

\textit{2018-2022} 

\qquad \textbf{Ph.D. researcher}: German Center for Integrative Biodiversity Research (iDiv) Halle-Jena-Leipzig, Leipzig, Germany. Ph.D. thesis: "From trees to soil: microbial and spatial mediation of tree diversity effects on carbon cycling in subtropical Chinese forests." (supervision: Prof. Dr. Nico Eisenhauer, Dr. Simone Cesarz)

\textit{2018} 

\qquad\textbf{Master's student}: Institut des Sciences de l'Evolution de Montpellier (ISEM), Montpellier, France. MSc thesis: "Modelling non-trophic interactions effects on community dynamics." (supervision Dr. Sonia Kéfi, Dr. Vasilis Dakos)

\textit{2017} 

\qquad \textbf{Intern}: Swedish University of Agricultural Sciences (SLU), Umeå, Sweden. Internship: "Root trait effects of alpine plant communities on plant-soil feedback effects performed in two greenhouse experiments." (supervision Dr. Paul Kardol)

\end{hangparas}
```
# Publications

I am actively steering my research towards interdisciplinary and transdisciplinary approaches. A key aspect of this endeavor is the deliberate inclusion of relevant collaborators, aimed at consolidating expertise and fostering collaboration across fields. The majority of my productions result from genuine collaboration, where each co-author contributes a unique aspect and perspective, often resulting in synthesis work across diverse fields. I am committed to being deeply involved in the data collection, data analyses, and/or visualization processes for articles I co-author, in addition to manuscript writing. To ensure fairness among co-authors, I have implemented a practice of randomizing co-author order, with exceptions for the first, second, and senior authors.

Decisions regarding the outlet for publication are made collectively among co-authors, guided by certain principles. These include a preference for open-access outlets, ensuring optimal visibility for results, and a strict avoidance of potential predatory journals listed in Beall's list and by mutual agreement among co-authors. In alignment with a commitment to transparency and open science, I take pride in publishing both related data and analysis scripts in public repositories alongside my scientific results. Furthermore, I actively support science communication initiatives. For instance, during the COVID-19 pandemic, I developed and maintained a virtual exhibition of our labs and its Instagram account, and I have contributed to the creation of a scientific article collection for teenagers on "Soil Biodiversity" in Frontiers for Young Minds. My overarching goal is to share research findings widely with the broader community.

## Publication summary

```{r fig.height=2.5, fig.width=5.5,message=FALSE, warning=FALSE, paged.print=FALSE, fig.align = 'center', echo = F}
library(tidyverse)

df = 
  readxl::read_xlsx('beugnon_scientific-profile.xlsx', 5)|> 
  mutate(Position = factor(Position, levels = c('First', 'Second', 'Co-author')))

df.cite = 
  readxl::read_xlsx('beugnon_scientific-profile.xlsx', 6)


ggplot() + 
   geom_bar(data = df.cite, aes(x = year, y = number*25/100),
            stat = 'identity', fill = 'grey80') + 
  geom_point(data = df |> filter(IF != 'NEW') |>
                 group_by(Year) |>
                 summarise(m = mean(as.numeric(IF)),
                           sd = sd(as.numeric(IF))), 
               aes(x = Year, y = m), size = 5) +
  geom_point(data = df |> filter(IF != 'NEW'), 
             aes(x = Year, y =as.numeric(IF),
                 color = Position, label = Name),
             size = 2) + 
  geom_point(data = df |> filter(IF == 'NEW'), 
             aes(x = Year, y =-2, 
                 color = Position, label = Name),
             size = 2) + 
  scale_y_continuous(breaks = c(-2,0,5,10,15,20, 25), 
                     labels = c('No IF',0,5,10,15,20, 25),
                     sec.axis = sec_axis( trans=~.*100/25, name = "Citations")) +
  scale_colour_manual(values = c('darkred','orange','blue')) + 
  geom_hline(yintercept = 0) +
  lims(x = c(2018, 2025)) + 
  labs(x = 'Year', 
       y = 'Journal IF', 
       color = 'Authorships') +
  theme_bw() + 
  theme(legend.position = 'right',
        panel.grid = element_blank())
```

**Publications and citations summary.** Black dots depict the average journal impact factor, while colored dots represent individual publications (colored per authorship position, left axis). New outlets without impact factor are annotated "No IF". Barplots illustrate the total number of citations per year (source: Google Scholar, right axis).

\vspace{1mm}

|            **2019 - 2024** (OA: Open Access)            | Total | First author (co-author) | Senior or corresponding author |
|:-----------------------------:|:------------:|:------------:|:------------:|
|          Advances in Ecological Research (OA)           |   1   |            1             |               1                |
|               Communications Biology (OA)               |   1   |           (1)            |               0                |
|             Comm. Earth & Environement (OA)             |   1   |           (1)            |               0                |
|               Ecological Monographs (OA)                |   1   |            1             |               1                |
|               Environmental Microbiology                |   1   |           (1)            |               0                |
|  Frontiers in Cellular and Infection Microbiology (OA)  |   1   |           (1)            |               0                |
|             Frontiers in Plant Science (OA)             |   1   |           (1)            |               0                |
|                ISME Communications (OA)                 |   1   |            1             |               1                |
| Journal of Sustainable Agriculture and Environment (OA) |   2   |          1 (1)           |               1                |
|               Microbiology Spectrum (OA)                |   1   |           (1)            |               0                |
|              National Science Review (OA)               |   1   |           (1)            |               0                |
|                       Oikos (OA)                        |   1   |            1             |               1                |
|                  Science Advances (OA)                  |   1   |           (1)            |               0                |
|                  Scientific data (OA)                   |   1   |           (1)            |               0                |
|                   Soil Organisms (OA)                   |   1   |           (1)            |               0                |

\vspace{1 mm}

Complete list of publications there: <https://remybeugnon.netlify.app/publication/>

## Selected publications

**Beugnon, R.**^+^, Albert, G., Hähn, G., Haider, S., Hättenschwiler, S., et al. (2023). Improving forest ecosystem functions by optimizing tree species spatial arrangement. *bioRxiv*. [10.1101/2023.10.23.563583](#0){.uri}. Lead author of this mathemartical modeling-based manuscript showing the importance of tree species spatial organization in optimizing ecosystem functioning (under minor revision in Nature Communications).

\vspace{4mm}

**Beugnon, R.**^+^, Bu, W., Bruelheide, H., Davrinche, A., Du, J., et al. (2023). Abiotic and biotic drivers of tree trait effects on soil microbial biomass and soil carbon concentration. *Ecological Monographs*. [10.1002/ecm.1563](#0){.uri}. Lead author of this synthesis paper revealing the mechanisms underlying the impact of tree species richness on soil microbial communities and carbon concentration.

\vspace{4mm}

**Beugnon, R.**^+^, Du, J., Cesarz, S., Jurburg, S. D., Pang, Z., et al. (2021). Tree diversity and soil chemical properties drive the linkages between soil microbial community and ecosystem functioning. *ISME Communications*. [10.1038/s43705-021-00040-0](#0){.uri}. Lead author of this synthesis paper revealing the effects of tree species richness and soil quality on soil microbial facets and the consequences for ecosystem functioning.

\vspace{4mm}

**Beugnon, R.**^+^, Eisenhauer, N., Bruelheide, H., Davrinche, A., Du, J., et al. (2023). Tree diversity effects on litter decomposition are mediated by litterfall and microbial processes. *Oikos*. [10.1111/oik.09751](#0){.uri}. Lead author of this publication investigating the mechanisms underlying the impact of tree diversity on leaf litter decomposition. The study explores the mediation of these effects by soil microbial communities through various field decomposition experiments.

\vspace{4mm}

**Beugnon, R.**^+^, Ladouceur, E., Sünnemann, M., Cesarz, S., & Eisenhauer, N. (2021). Diverse forests are cool: Promoting diverse forests to mitigate carbon emissions and climate change. *Journal of Sustainable Agriculture and Environment*. [10.1002/sae2.12005](https://doi.org/10.1002/sae2.12005){.uri}. Lead author of this perspective piece emphasizing the potential benefits of diversifying forest plantations to optimize reforestation projects benefits and sustainability.

\vspace{4mm}

**Beugnon, R.**^+^, Le Guyader, N., Milcu, A., Lenoir, J., Puissant, J., et al. (under review). Microclimate modulation: an overlooked mechanism influencing the impact of plant diversity on ecosystem functioning. *Global Change Biology*. Lead author of this perspective piece emphasizing the potential of plant diversity to affect ecosystem functioning through the modification of microclimate, thus to mitigate the impact of climate change on ecosystem functioning (Under minor revision in Global Change Biology, available in the supplementary material). **Conducted independently from my Ph.D. supervisors.**

\vspace{4mm}

Eisenhauer, N.^+^, Angst, G., Asato, A. E. B., **Beugnon, R.**, Bönisch, E., et al. (2023). The heterogeneity--diversity--system performance nexus. *National Science Review*. [10.1093/nsr/nwad109](#0){.uri}. Co-author of this perspective article exploring the connections between heterogeneity, diversity, and system performances across various fields, where I brought a specific focus on spatial and temporal aspects.

\vspace{4mm}

Kemppinen, J.^+^, Lembrechts, J. J., Van Meerbeek, K., Carnicer, J., Chardon, ... **Beugnon, R.**, et al. (2023). Microclimate, an inseparable part of ecology and biogeography. *bioRxiv* [10.5281/ZENODO.7973314](#0){.uri}. Co-author of this perspective manuscript synthesizing the current state and perspectives of microclimate research, where I focused on modeling techniques (under final review in GCB, **Conducted independently from my Ph.D. supervisors**).

\vspace{4mm}

Schnabel, F.^+^, **Beugnon, R.**^+^, Yang, B.^+^, Richter, R., Eisenhauer, N., et al. (2023). Tree diversity increases forest temperature buffering. *bioRxiv*. [10.1101/2023.09.11.556807](#0){.uri}. Co-lead authors of this data paper exploring the effects on tree species richness on forest microclimate. We highlighted the tree species richness buffering effect on air temperature and its functional drivers over time (under review in Nature Communications).

# Data & codes

## Datasets and databases

-   SoilTemp database: <https://www.soiltempproject.com/> - **elected to the Steering Committee**, responsible of the database technical development.

-   Phillips, H. R. P., Bach, E. M., Bartz, M. L. C., Bennett, J. M., **Beugnon, R.**, et al. (2021). Global data on earthworm abundance, biomass, diversity and corresponding environmental properties. *Scientific Data*. [10.1038/s41597-021-00912-z](#0){.uri}

## Codes & softwares

-   **Beugnon, R.** (2023). remybeugnon/Beugnon-et-al-2023-Oikos: Beugnon et al 2023 - Oikos (Article) [Computer software]. *Zenodo*. <10.5281/ZENODO.8039140>

-   **Beugnon, R.**, Bu, W., Bruelheide, H., Davrinche, A., Du, J., et al. (2022). remybeugnon/Beugnon-et-al-2021_Soil-carbon-and-microbial-biomass-drivers: Major revision of the analyses during review process [Computer software]. *Zenodo*. [10.5281/zenodo.7225739](#0){.uri}

-   Lutrat, C., & **Beugnon, R.** (2023). Celia-Lutrat/Lutrat-et-al_2023_GSS: Release version 1.1.0 (v1.1.0) [Computer software]. *Zenodo*. <10.5281/ZENODO.8032932>

-   Sünnemann, M., & **Beugnon, R.** (2023). Mariesuennemann/Suennemann-et-al-2023_Multifunctionality (publication-scripts) [Computer software]. *Zenodo*. <10.5281/ZENODO.8386710>

# Awards

*2021* Science Communication Prize (iDiv), Awarded for the collection "Soil Biodiversity" in Frontiers for Young Minds, the lab Instagram channel, a lab virtual gallery (500€).

# Science communications

-   **eBook editor**: **Beugnon, R.**, Jochum, M., & Phillips, H. R. P. (2022). SOIL BIODIVERSITY collection. Frontiers Media S. <https://www.frontiersin.org/research-topics/11796/pdf>

-   **Interview for Eos:** Sidik, S. M. (2023), Diverse forests store more carbon than monocultures, *Eos, 104,* <10.1029/2023EO230464>.

# Talks & posters

*2023*

-   **Poster**: "Forest spatial heterogeneity & leaf litter dynamics" *Modeling in Ecology and Evolution* 24-26.05.2023 Montpellier, France.

*2022*

-   **Talk**: "Tree diversity increases air temperature buffering in forests" *Microclimate Ecology & Biogeagraphy* 29.08-01.09.2022 Antwerp, Belgium.

-   **Poster**: "Vegetation diversity buffers soil microclimatic extremes: phenomenon and mechanisms" *Microclimate Ecology & Biogeagraphy* 29.08-01.09.2022 Antwerp, Belgium.

-   **Poster**: "Vegetation diversity buffers soil microclimatic extremes: phenomenon and mechanisms" *World Biodiversity Forum* 26.06-01.07.2022 Davos, Switzeland.

*2021*

-   **Talk**: "Tree diversity - litterfall - decomposition" *EU Soil Observatory Conference* 21.10.2021 Online.

-   **Talk**: "Tree diversity - litterfall - decomposition" *GfÖ conference* 31.08-03.09.2021 Online.

*2020*

-   **Talk**: "Biotic and abiotic mediations of scale dependent tree trait effects on soil carbon concentration" *BES Conference* 14.12-18.12.2020 Online.

# Teaching

*2023*

-   **Leipzig University** (SS 2023) - Seminar series in the "Introduction to Ecology" bachelor.

-   **Leipzig University** (SS 2023) - Seminar series in "Introduction to Biodiversity" master.

-   **German Center for Integrative Biodiversity research (iDiv) Halle-Jena-Leipzig** (SS 2023) - Introduction to Structural Equation Modeling

*2022*

-   **German Center for Integrative Biodiversity research (iDiv) Halle-Jena-Leipzig** (SS 2022) - Introduction to Statistics in R

-   **Martin Luther University Halle-Wittenberg** (WS 2022) - Introduction to Structural Equation Modeling in the Introduction to scientific analyses master

*2021*

-   **Martin Luther University Halle-Wittenberg** (WS 2021) - Introduction to Structural Equation Modeling in the Introduction to scientific analyses master

# Supervision

*2023*

-   **Aurore Moulin**: M1 internship (4 months) - *ECOSYSTEMES master program, Montpellier University*, "Tree species richness effects on leaf nutrient resorption"

-   **Lucas Rey-Torrecillas**: Second year DUT (4 months) - *Technology in Data Sciences IUT Perpignan*, "Application utilisateur de validation des données"

-   **Nolwenn Le-Guyader**: ENS internship (3 months) - *ENS Lyon*, "Mise en place d'une expérience de terrain en Ste Baume"

*2021*

-   **Henriette Christel**: master thesis (1 year) - *Martin Luther University Halle-Wittenberg*, "Tree species identity and tree-tree interaction effects on soil microbial biomass and basal respiration"

*2019*

-   **Georg Hähn**: bachelor thesis (6 months) - *Martin Luther University Halle-Wittenberg*, "Litter quality and tree species richness effects on litter decomposition in subtropical forest"

Thesis and defense presentation can be found on <https://remybeugnon.netlify.app/people/>

# Reviews

Reviewer of scientific papers in Diversity and Distribution (2023), Ecological Applications (2023), Ecology Letters (2023), Functional Ecology (2023), Global Change Biology (2023), Nature Communications (2022), Pedobiologia (2020), Scientific Reports (2020), Soil Organisms (2019).

# Synthesis of past activities

I am exploring the impact of plant diversity on ecosystem functioning, with a specific focus on microclimate modulation. This research sits at the intersection of microclimate and biodiversity-ecosystem functioning research, pushing the boundaries of our understanding in these domains.

I began my academic journey as a trainee in agricultural engineering, where I joined a master's program in ecology and evolution during the final year. My master's thesis focused on modeling species interactions (ISEM, Montpellier, France), setting the stage for my Ph.D. on tree-tree interactions at iDiv (Leipzig, Germany). In my doctoral research, I delved into exploring the impact of tree species richness on the forest carbon cycle. This comprehensive study spanned aspects ranging from litterfall production to litter decomposition and soil carbon storage, encompassing an examination of soil microbial community functioning.

Recognizing the pivotal role of microclimate as a major driver of ecosystem functions during my Ph.D., I decided to shift my focus towards microclimate sciences. In response to a call from the SoilTemp project, I undertook the analysis of the effects of plant diversity on microclimate on a global scale. This endeavor led me to collaborate with the Leipzig Institute of Meteorology (LIM) in Leipzig (Germany), where I continue to explore the intricate interactions between plant diversity and microclimate.

\singlespacing

1.  **Publications (2019-2023)**: I published 16 peer-reviewed articles, including 5 as first author and prestigious outlets such as Science Advances (Impact Factor: 15) and Ecological Monographs (IF: 10). In addition, three first author articles are currently under review in Nature Communications (IF: 17), Science Advances (IF: 15), and Global Change Biology (IF: 12). \vspace{3mm}
2.  **Supervision**: I supervised 2 master's students, 1 bachelor's student, 1 gap year student from ENS Lyon, and 1 final-year student at the Perpignan University Institute of Technology (IUT). \vspace{3mm}
3.  **Lectures**: I delivered university lectures to bachelor's and master's students on Ecology (2023), Biodiversity (2023), and statistics (2021-2023). \vspace{3mm}
4.  **Expertise**: Technical report for the European Commission on the Soil Monitoring Law (project led by Carlos Guerra **independently from my Ph.D. supervisors**, preview in supplementary materials). \vspace{3mm}
5.  **Network**: I am leading an international panel of experts on decomposition in terrestrial ecosystems for the How-to-decompose project (<https://remybeugnon.netlify.app/project/how-to-decompose/>). This long-term project implies the interaction with the panel of collaborators, organization and animation of bi-annual online workshops, and preparation of funding proposals. \vspace{3mm}
6.  **Network:** I was elected to the SoilTemp database steering committee (**independently from my Ph.D. supervisors**). This current involvement implies the participation in the network organization, animation and development, committee meetings every semester, participation of the recruitment and supervision of students and postdocs. \vspace{3mm}
7.  **Outreach**: I was interviewed as an expert on Biodiversity-Ecosystem Functioning for EOS, a journal from the AGU (Sidik, S. M. (2023), Diverse forests store more carbon than monocultures, *Eos, 104,* <https://doi.org/10.1029/2023EO230464>. Published on 5 December 2023). \vspace{3mm}
8.  **Outreach**: I edited "Soil Biodiversity," a collection eBook in Frontiers for Young Minds, combining 33 articles on soil biodiversity from 50 scientists for kids and teenagers. **The project was not associated with my Ph.D. supervisors.** (Beugnon, R., Jochum, M., & Phillips, H. R. P. (2022). *SOIL BIODIVERSITY*. Frontiers Media S <https://www.frontiersin.org/research-topics/11796/pdf>)

```{=tex}
\fancyfoot[C]{
he/him - 27 Allée du Pic de Nore, 34090 Montpellier - +33 6 77 56 55 79 -  remy.beugnon@idiv.de - remybeugnon.netlify.app - X: @BeugnonRemy - GitHub: @remybeugnon}
```
