---
title: Which reference manager should I use? 
author: 'admin'
slug: reference-manager
subtitle: ''
summary: ''
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
categories: ["literature"]
tags: ["literature"]
authors: ['admin']
lastmod: '2021-10-11T10:56:08+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
---

You can find numerous ways to manage your literature research and database. With the increasing number of papers published in every field, manual archiving has become impossible. Reference managers become a critical tool to manage your reference database, dive into the database, extract the relevant references for publication, and format your citations. Thus, numerous reference managers have exponentially increased in the past decades. I was struggling in the past few weeks with my previous choice and how to choose a good one. Here are some keys to find the reference manager which fits you.\
**Spoiler alert**: there is no good solution, only options that will fit more or less to your way of working.

# What are the current options?

More and more references managers have become available in the past few years, here, are some of the most used in ecology and evolution:

-   Citavi ([webpage](https://www.citavi.com/en)): possibility to build ordered knowledge contents and quote from PDF

-   EndNote ([webpage](https://endnote.com/))

-   JabRef ([webpage](https://www.jabref.org/)): BibTex-based database built under Java but no MSWord plugging

-   Mendeley ([webpage](https://www.mendeley.com/)): maybe the most-used reference manager

-   Paperpile ([webpage](https://paperpile.com/)): made to work with GoogleDocs

-   Sciwheel ([webpage](https://sciwheel.com/?lg))

-   Zotero ([webpage](https://www.zotero.org/)): Implemented in MSWord, R Markdown, and GoogleDocs (with some issues with GoogleDocs)

# What are people using these days?

After a small pool on tweeter and in my lab:

<blockquote class="twitter-tweet">

<p lang="en" dir="ltr">

❓❓❓QUESTION❓❓❓<br><br>Which reference manager are you using? Tell me why in the comment if you have a real good reason for it! <br><br>(I am sure this has been asked a thousand time 🤔)

</p>

--- Rémy Beugnon (@BeugnonRemy) \<a href="<https://twitter.com/BeugnonRemy/status/1448284744962166784?ref_src=twsrc%5Etfw%22October> 13, 2021</a>

</blockquote>

```{=html}
<script async src="https://platform.twitter.com/widgets.js" 
charset="utf-8"></script>
```
```{r, echo = F, warning=F, message=F}
df = data.frame(
  `Reference manager` = c('Citavi', 'EndNote',"JabRef",'Mendeley',"Paperpile",'Sciwheel','Zotero'),
  Rate = c(0.061, 0.135, 0.012, 0.427, 0.012,0.012,0.354), 
  Label = c(0.061, 0.135, 0.012, 0.427, 0.012,0.012,0.354)*100
)
library(ggplot2)
ggplot(df[order(df$Rate),], aes(x="", y=Rate, fill=`Reference.manager`)) +
  geom_bar(stat="identity", 
           width=1,
           color = 'white') +
  coord_polar("y", start=0) + 
  labs(fill = 'Reference manager') + 
  theme_void()
```

# Some useful links

Full comparison by TUM: <https://mediatum.ub.tum.de/node?id=1127579>

Blog posts: <https://www.drsotayo.com/five-reference-management-platforms-for-students-and-researchers/>
